version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: sirarom_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    restart: always
    networks:
      - sirarom_net

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    depends_on:
      - db
    restart: always
    networks:
      - sirarom_net

  app:
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
      - "8500:8500"
    # environment:
    #   - DB_HOST=localhost
    #   - DB_PORT=5432
    #   - DB_USER=admin
    #   - DB_PASSWORD=password
    #   - DB_NAME=sirarom_db
    depends_on:
      - db
    restart: always
    networks:
      - sirarom_net

networks:
  sirarom_net:
    driver: bridge